/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitPayApi);
  }
}(this, function(expect, GitPayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GitPayApi.PaymentDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentDetails', function() {
    it('should create an instance of PaymentDetails', function() {
      // uncomment below and update the code to test PaymentDetails
      //var instane = new GitPayApi.PaymentDetails();
      //expect(instance).to.be.a(GitPayApi.PaymentDetails);
    });

    it('should have the property paymentAccount (base name: "PaymentAccount")', function() {
      // uncomment below and update the code to test the property paymentAccount
      //var instane = new GitPayApi.PaymentDetails();
      //expect(instance).to.be();
    });

    it('should have the property paymentBank (base name: "PaymentBank")', function() {
      // uncomment below and update the code to test the property paymentBank
      //var instane = new GitPayApi.PaymentDetails();
      //expect(instance).to.be();
    });

    it('should have the property paymentBankBik (base name: "PaymentBankBik")', function() {
      // uncomment below and update the code to test the property paymentBankBik
      //var instane = new GitPayApi.PaymentDetails();
      //expect(instance).to.be();
    });

    it('should have the property paymentBankAccount (base name: "PaymentBankAccount")', function() {
      // uncomment below and update the code to test the property paymentBankAccount
      //var instane = new GitPayApi.PaymentDetails();
      //expect(instance).to.be();
    });

    it('should have the property paymentBankKpp (base name: "PaymentBankKpp")', function() {
      // uncomment below and update the code to test the property paymentBankKpp
      //var instane = new GitPayApi.PaymentDetails();
      //expect(instance).to.be();
    });

    it('should have the property paymentBankInn (base name: "PaymentBankInn")', function() {
      // uncomment below and update the code to test the property paymentBankInn
      //var instane = new GitPayApi.PaymentDetails();
      //expect(instance).to.be();
    });

    it('should have the property paymentBankOKPO (base name: "PaymentBankOKPO")', function() {
      // uncomment below and update the code to test the property paymentBankOKPO
      //var instane = new GitPayApi.PaymentDetails();
      //expect(instance).to.be();
    });

    it('should have the property paymentBankOGRN (base name: "PaymentBankOGRN")', function() {
      // uncomment below and update the code to test the property paymentBankOGRN
      //var instane = new GitPayApi.PaymentDetails();
      //expect(instance).to.be();
    });

  });

}));
