/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitPayApi);
  }
}(this, function(expect, GitPayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GitPayApi.UserSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserSettings', function() {
    it('should create an instance of UserSettings', function() {
      // uncomment below and update the code to test UserSettings
      //var instane = new GitPayApi.UserSettings();
      //expect(instance).to.be.a(GitPayApi.UserSettings);
    });

    it('should have the property userId (base name: "UserId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new GitPayApi.UserSettings();
      //expect(instance).to.be();
    });

    it('should have the property gitHubLogin (base name: "GitHubLogin")', function() {
      // uncomment below and update the code to test the property gitHubLogin
      //var instane = new GitPayApi.UserSettings();
      //expect(instance).to.be();
    });

    it('should have the property registeredDate (base name: "RegisteredDate")', function() {
      // uncomment below and update the code to test the property registeredDate
      //var instane = new GitPayApi.UserSettings();
      //expect(instance).to.be();
    });

    it('should have the property userDisplayName (base name: "UserDisplayName")', function() {
      // uncomment below and update the code to test the property userDisplayName
      //var instane = new GitPayApi.UserSettings();
      //expect(instance).to.be();
    });

    it('should have the property userAvatarURL (base name: "UserAvatarURL")', function() {
      // uncomment below and update the code to test the property userAvatarURL
      //var instane = new GitPayApi.UserSettings();
      //expect(instance).to.be();
    });

    it('should have the property userEmail (base name: "UserEmail")', function() {
      // uncomment below and update the code to test the property userEmail
      //var instane = new GitPayApi.UserSettings();
      //expect(instance).to.be();
    });

    it('should have the property billingDetails (base name: "BillingDetails")', function() {
      // uncomment below and update the code to test the property billingDetails
      //var instane = new GitPayApi.UserSettings();
      //expect(instance).to.be();
    });

    it('should have the property contractSettings (base name: "ContractSettings")', function() {
      // uncomment below and update the code to test the property contractSettings
      //var instane = new GitPayApi.UserSettings();
      //expect(instance).to.be();
    });

  });

}));
