/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitPayApi);
  }
}(this, function(expect, GitPayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GitPayApi.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('addUserPull', function() {
      it('should call addUserPull successfully', function(done) {
        //uncomment below and update the code to test addUserPull
        //instance.addUserPull(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addUserRepo', function() {
      it('should call addUserRepo successfully', function(done) {
        //uncomment below and update the code to test addUserRepo
        //instance.addUserRepo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserDeals', function() {
      it('should call getUserDeals successfully', function(done) {
        //uncomment below and update the code to test getUserDeals
        //instance.getUserDeals(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserEvents', function() {
      it('should call getUserEvents successfully', function(done) {
        //uncomment below and update the code to test getUserEvents
        //instance.getUserEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserPulls', function() {
      it('should call getUserPulls successfully', function(done) {
        //uncomment below and update the code to test getUserPulls
        //instance.getUserPulls(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserRepos', function() {
      it('should call getUserRepos successfully', function(done) {
        //uncomment below and update the code to test getUserRepos
        //instance.getUserRepos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserSettings', function() {
      it('should call getUserSettings successfully', function(done) {
        //uncomment below and update the code to test getUserSettings
        //instance.getUserSettings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeUserPull', function() {
      it('should call removeUserPull successfully', function(done) {
        //uncomment below and update the code to test removeUserPull
        //instance.removeUserPull(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeUserRepo', function() {
      it('should call removeUserRepo successfully', function(done) {
        //uncomment below and update the code to test removeUserRepo
        //instance.removeUserRepo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserSettings', function() {
      it('should call updateUserSettings successfully', function(done) {
        //uncomment below and update the code to test updateUserSettings
        //instance.updateUserSettings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
