/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DealType.
* @enum {}
* @readonly
*/
export default class DealType {
    
        /**
         * value: "Deferred"
         * @const
         */
        "Deferred" = "Deferred";

    
        /**
         * value: "Instant"
         * @const
         */
        "Instant" = "Instant";

    

    /**
    * Returns a <code>DealType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DealType} The enum <code>DealType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

