/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DealState from './DealState';
import DealType from './DealType';

/**
 * The DealInfo model module.
 * @module model/DealInfo
 * @version 0.0.1
 */
class DealInfo {
    /**
     * Constructs a new <code>DealInfo</code>.
     * @alias module:model/DealInfo
     */
    constructor() { 
        
        DealInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DealInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DealInfo} obj Optional instance to populate.
     * @return {module:model/DealInfo} The populated <code>DealInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DealInfo();

            if (data.hasOwnProperty('PlatformDealId')) {
                obj['PlatformDealId'] = ApiClient.convertToType(data['PlatformDealId'], 'String');
            }
            if (data.hasOwnProperty('DealStateId')) {
                obj['DealStateId'] = DealState.constructFromObject(data['DealStateId']);
            }
            if (data.hasOwnProperty('CreateDate')) {
                obj['CreateDate'] = ApiClient.convertToType(data['CreateDate'], 'Date');
            }
            if (data.hasOwnProperty('UpdateDate')) {
                obj['UpdateDate'] = ApiClient.convertToType(data['UpdateDate'], 'Date');
            }
            if (data.hasOwnProperty('ExpireDate')) {
                obj['ExpireDate'] = ApiClient.convertToType(data['ExpireDate'], 'Date');
            }
            if (data.hasOwnProperty('Amount')) {
                obj['Amount'] = ApiClient.convertToType(data['Amount'], 'Number');
            }
            if (data.hasOwnProperty('CurrencyId')) {
                obj['CurrencyId'] = ApiClient.convertToType(data['CurrencyId'], 'Number');
            }
            if (data.hasOwnProperty('PlatformPayerId')) {
                obj['PlatformPayerId'] = ApiClient.convertToType(data['PlatformPayerId'], 'String');
            }
            if (data.hasOwnProperty('PayerPhoneNumber')) {
                obj['PayerPhoneNumber'] = ApiClient.convertToType(data['PayerPhoneNumber'], 'String');
            }
            if (data.hasOwnProperty('PayerPaymentToolId')) {
                obj['PayerPaymentToolId'] = ApiClient.convertToType(data['PayerPaymentToolId'], 'Number');
            }
            if (data.hasOwnProperty('PlatformBeneficiaryId')) {
                obj['PlatformBeneficiaryId'] = ApiClient.convertToType(data['PlatformBeneficiaryId'], 'String');
            }
            if (data.hasOwnProperty('BeneficiaryPaymentToolId')) {
                obj['BeneficiaryPaymentToolId'] = ApiClient.convertToType(data['BeneficiaryPaymentToolId'], 'String');
            }
            if (data.hasOwnProperty('ShortDescription')) {
                obj['ShortDescription'] = ApiClient.convertToType(data['ShortDescription'], 'Number');
            }
            if (data.hasOwnProperty('FullDescription')) {
                obj['FullDescription'] = ApiClient.convertToType(data['FullDescription'], 'String');
            }
            if (data.hasOwnProperty('DealTypeId')) {
                obj['DealTypeId'] = DealType.constructFromObject(data['DealTypeId']);
            }
            if (data.hasOwnProperty('LastErrorCode')) {
                obj['LastErrorCode'] = ApiClient.convertToType(data['LastErrorCode'], 'String');
            }
            if (data.hasOwnProperty('LastErrorMessage')) {
                obj['LastErrorMessage'] = ApiClient.convertToType(data['LastErrorMessage'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} PlatformDealId
 */
DealInfo.prototype['PlatformDealId'] = undefined;

/**
 * @member {module:model/DealState} DealStateId
 */
DealInfo.prototype['DealStateId'] = undefined;

/**
 * @member {Date} CreateDate
 */
DealInfo.prototype['CreateDate'] = undefined;

/**
 * @member {Date} UpdateDate
 */
DealInfo.prototype['UpdateDate'] = undefined;

/**
 * @member {Date} ExpireDate
 */
DealInfo.prototype['ExpireDate'] = undefined;

/**
 * @member {Number} Amount
 */
DealInfo.prototype['Amount'] = undefined;

/**
 * @member {Number} CurrencyId
 */
DealInfo.prototype['CurrencyId'] = undefined;

/**
 * @member {String} PlatformPayerId
 */
DealInfo.prototype['PlatformPayerId'] = undefined;

/**
 * @member {String} PayerPhoneNumber
 */
DealInfo.prototype['PayerPhoneNumber'] = undefined;

/**
 * @member {Number} PayerPaymentToolId
 */
DealInfo.prototype['PayerPaymentToolId'] = undefined;

/**
 * @member {String} PlatformBeneficiaryId
 */
DealInfo.prototype['PlatformBeneficiaryId'] = undefined;

/**
 * @member {String} BeneficiaryPaymentToolId
 */
DealInfo.prototype['BeneficiaryPaymentToolId'] = undefined;

/**
 * @member {Number} ShortDescription
 */
DealInfo.prototype['ShortDescription'] = undefined;

/**
 * @member {String} FullDescription
 */
DealInfo.prototype['FullDescription'] = undefined;

/**
 * @member {module:model/DealType} DealTypeId
 */
DealInfo.prototype['DealTypeId'] = undefined;

/**
 * @member {String} LastErrorCode
 */
DealInfo.prototype['LastErrorCode'] = undefined;

/**
 * @member {String} LastErrorMessage
 */
DealInfo.prototype['LastErrorMessage'] = undefined;






export default DealInfo;

