/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DealState.
* @enum {}
* @readonly
*/
export default class DealState {
    
        /**
         * value: "Created"
         * @const
         */
        "Created" = "Created";

    
        /**
         * value: "Paid"
         * @const
         */
        "Paid" = "Paid";

    
        /**
         * value: "PayoutProcessError"
         * @const
         */
        "PayoutProcessError" = "PayoutProcessError";

    
        /**
         * value: "CancelError"
         * @const
         */
        "CancelError" = "CancelError";

    
        /**
         * value: "PayoutProcessing"
         * @const
         */
        "PayoutProcessing" = "PayoutProcessing";

    
        /**
         * value: "Completed"
         * @const
         */
        "Completed" = "Completed";

    
        /**
         * value: "PaymentHold"
         * @const
         */
        "PaymentHold" = "PaymentHold";

    
        /**
         * value: "Canceling"
         * @const
         */
        "Canceling" = "Canceling";

    
        /**
         * value: "Canceled"
         * @const
         */
        "Canceled" = "Canceled";

    

    /**
    * Returns a <code>DealState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DealState} The enum <code>DealState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

