/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Event model module.
 * @module model/Event
 * @version 0.0.1
 */
class Event {
    /**
     * Constructs a new <code>Event</code>.
     * @alias module:model/Event
     */
    constructor() { 
        
        Event.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Event} obj Optional instance to populate.
     * @return {module:model/Event} The populated <code>Event</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Event();

            if (data.hasOwnProperty('EventId')) {
                obj['EventId'] = ApiClient.convertToType(data['EventId'], 'String');
            }
            if (data.hasOwnProperty('EventType')) {
                obj['EventType'] = ApiClient.convertToType(data['EventType'], 'String');
            }
            if (data.hasOwnProperty('CreateDate')) {
                obj['CreateDate'] = ApiClient.convertToType(data['CreateDate'], 'Date');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('Payload')) {
                obj['Payload'] = ApiClient.convertToType(data['Payload'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * @member {String} EventId
 */
Event.prototype['EventId'] = undefined;

/**
 * @member {String} EventType
 */
Event.prototype['EventType'] = undefined;

/**
 * @member {Date} CreateDate
 */
Event.prototype['CreateDate'] = undefined;

/**
 * @member {String} Description
 */
Event.prototype['Description'] = undefined;

/**
 * @member {Object.<String, Object>} Payload
 */
Event.prototype['Payload'] = undefined;






export default Event;

