/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentDetails model module.
 * @module model/PaymentDetails
 * @version 0.0.1
 */
class PaymentDetails {
    /**
     * Constructs a new <code>PaymentDetails</code>.
     * @alias module:model/PaymentDetails
     */
    constructor() { 
        
        PaymentDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentDetails} obj Optional instance to populate.
     * @return {module:model/PaymentDetails} The populated <code>PaymentDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentDetails();

            if (data.hasOwnProperty('PaymentAccount')) {
                obj['PaymentAccount'] = ApiClient.convertToType(data['PaymentAccount'], 'String');
            }
            if (data.hasOwnProperty('PaymentBank')) {
                obj['PaymentBank'] = ApiClient.convertToType(data['PaymentBank'], 'String');
            }
            if (data.hasOwnProperty('PaymentBankBik')) {
                obj['PaymentBankBik'] = ApiClient.convertToType(data['PaymentBankBik'], 'String');
            }
            if (data.hasOwnProperty('PaymentBankAccount')) {
                obj['PaymentBankAccount'] = ApiClient.convertToType(data['PaymentBankAccount'], 'String');
            }
            if (data.hasOwnProperty('PaymentBankKpp')) {
                obj['PaymentBankKpp'] = ApiClient.convertToType(data['PaymentBankKpp'], 'String');
            }
            if (data.hasOwnProperty('PaymentBankInn')) {
                obj['PaymentBankInn'] = ApiClient.convertToType(data['PaymentBankInn'], 'String');
            }
            if (data.hasOwnProperty('PaymentBankOKPO')) {
                obj['PaymentBankOKPO'] = ApiClient.convertToType(data['PaymentBankOKPO'], 'String');
            }
            if (data.hasOwnProperty('PaymentBankOGRN')) {
                obj['PaymentBankOGRN'] = ApiClient.convertToType(data['PaymentBankOGRN'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} PaymentAccount
 */
PaymentDetails.prototype['PaymentAccount'] = undefined;

/**
 * @member {String} PaymentBank
 */
PaymentDetails.prototype['PaymentBank'] = undefined;

/**
 * @member {String} PaymentBankBik
 */
PaymentDetails.prototype['PaymentBankBik'] = undefined;

/**
 * @member {String} PaymentBankAccount
 */
PaymentDetails.prototype['PaymentBankAccount'] = undefined;

/**
 * @member {String} PaymentBankKpp
 */
PaymentDetails.prototype['PaymentBankKpp'] = undefined;

/**
 * @member {String} PaymentBankInn
 */
PaymentDetails.prototype['PaymentBankInn'] = undefined;

/**
 * @member {String} PaymentBankOKPO
 */
PaymentDetails.prototype['PaymentBankOKPO'] = undefined;

/**
 * @member {String} PaymentBankOGRN
 */
PaymentDetails.prototype['PaymentBankOGRN'] = undefined;






export default PaymentDetails;

