/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentDetails from './PaymentDetails';

/**
 * The UserSettingsContractSettings model module.
 * @module model/UserSettingsContractSettings
 * @version 0.0.1
 */
class UserSettingsContractSettings {
    /**
     * Constructs a new <code>UserSettingsContractSettings</code>.
     * Данные, выносимые при создании договора
     * @alias module:model/UserSettingsContractSettings
     */
    constructor() { 
        
        UserSettingsContractSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserSettingsContractSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserSettingsContractSettings} obj Optional instance to populate.
     * @return {module:model/UserSettingsContractSettings} The populated <code>UserSettingsContractSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserSettingsContractSettings();

            if (data.hasOwnProperty('Sex')) {
                obj['Sex'] = ApiClient.convertToType(data['Sex'], 'String');
            }
            if (data.hasOwnProperty('Inn')) {
                obj['Inn'] = ApiClient.convertToType(data['Inn'], 'String');
            }
            if (data.hasOwnProperty('DateOfBirth')) {
                obj['DateOfBirth'] = ApiClient.convertToType(data['DateOfBirth'], 'Date');
            }
            if (data.hasOwnProperty('PassportDetails')) {
                obj['PassportDetails'] = ApiClient.convertToType(data['PassportDetails'], 'String');
            }
            if (data.hasOwnProperty('Address')) {
                obj['Address'] = ApiClient.convertToType(data['Address'], 'String');
            }
            if (data.hasOwnProperty('PaymentDetails')) {
                obj['PaymentDetails'] = PaymentDetails.constructFromObject(data['PaymentDetails']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} Sex
 */
UserSettingsContractSettings.prototype['Sex'] = undefined;

/**
 * @member {String} Inn
 */
UserSettingsContractSettings.prototype['Inn'] = undefined;

/**
 * @member {Date} DateOfBirth
 */
UserSettingsContractSettings.prototype['DateOfBirth'] = undefined;

/**
 * @member {String} PassportDetails
 */
UserSettingsContractSettings.prototype['PassportDetails'] = undefined;

/**
 * @member {String} Address
 */
UserSettingsContractSettings.prototype['Address'] = undefined;

/**
 * @member {module:model/PaymentDetails} PaymentDetails
 */
UserSettingsContractSettings.prototype['PaymentDetails'] = undefined;






export default UserSettingsContractSettings;

