/**
 * GitPay API
 * Is developed as a part of gitpay.ru project by Microbo team 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: alexandrdavydenko@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BillingAccount from './BillingAccount';
import UserSettingsContractSettings from './UserSettingsContractSettings';

/**
 * The UserSettings model module.
 * @module model/UserSettings
 * @version 0.0.1
 */
class UserSettings {
    /**
     * Constructs a new <code>UserSettings</code>.
     * @alias module:model/UserSettings
     */
    constructor() { 
        
        UserSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserSettings} obj Optional instance to populate.
     * @return {module:model/UserSettings} The populated <code>UserSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserSettings();

            if (data.hasOwnProperty('UserId')) {
                obj['UserId'] = ApiClient.convertToType(data['UserId'], 'String');
            }
            if (data.hasOwnProperty('GitHubLogin')) {
                obj['GitHubLogin'] = ApiClient.convertToType(data['GitHubLogin'], 'String');
            }
            if (data.hasOwnProperty('RegisteredDate')) {
                obj['RegisteredDate'] = ApiClient.convertToType(data['RegisteredDate'], 'Date');
            }
            if (data.hasOwnProperty('UserDisplayName')) {
                obj['UserDisplayName'] = ApiClient.convertToType(data['UserDisplayName'], 'String');
            }
            if (data.hasOwnProperty('UserAvatarURL')) {
                obj['UserAvatarURL'] = ApiClient.convertToType(data['UserAvatarURL'], 'String');
            }
            if (data.hasOwnProperty('UserEmail')) {
                obj['UserEmail'] = ApiClient.convertToType(data['UserEmail'], 'String');
            }
            if (data.hasOwnProperty('BillingDetails')) {
                obj['BillingDetails'] = BillingAccount.constructFromObject(data['BillingDetails']);
            }
            if (data.hasOwnProperty('ContractSettings')) {
                obj['ContractSettings'] = UserSettingsContractSettings.constructFromObject(data['ContractSettings']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} UserId
 */
UserSettings.prototype['UserId'] = undefined;

/**
 * @member {String} GitHubLogin
 */
UserSettings.prototype['GitHubLogin'] = undefined;

/**
 * @member {Date} RegisteredDate
 */
UserSettings.prototype['RegisteredDate'] = undefined;

/**
 * @member {String} UserDisplayName
 */
UserSettings.prototype['UserDisplayName'] = undefined;

/**
 * @member {String} UserAvatarURL
 */
UserSettings.prototype['UserAvatarURL'] = undefined;

/**
 * @member {String} UserEmail
 */
UserSettings.prototype['UserEmail'] = undefined;

/**
 * @member {module:model/BillingAccount} BillingDetails
 */
UserSettings.prototype['BillingDetails'] = undefined;

/**
 * @member {module:model/UserSettingsContractSettings} ContractSettings
 */
UserSettings.prototype['ContractSettings'] = undefined;






export default UserSettings;

